version: '2'

services:
  db:
    restart: always
    image: mongo:3.2.3
    volumes:
      - ./data/db:/data/db

  server:
    environment:
      - SITE_URL="http://localhost:9000"
      - ADMIN_USERNAME="admin"
    depends_on:
      - db
    restart: always
    build: .
    ports:
      - 127.0.0.1:9000:9000
    links:
      - db:mongodb
    volumes:
      - ./data/upload:/usr/local/leanote/public/upload
      - ./data/files:/usr/local/leanote/files

